config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "offers#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  resources :users, only: %i[show] do
    resources :appointments, only: %i[index]
  end

  resources :offers, only: %i[index new create show destroy edit update] do
    resources :appointments, only: %i[new create destroy update edit]
  end
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :offer
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :appointments
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :title, :description, :hourly_rate, :location, :photo, :category, presence: true
  validates :category, inclusion: { in: %w[Home Sports Education Pets Arts Music Garden Other] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :offers
  has_many :appointments
  validates :email, :password, presence: true
  validates :email, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def new
    @appointment = Appointment.new
    @offer = Offer.find(params[:offer_id])
  end

  def create
    @offer = Offer.find(params[:offer_id])
    @appointment = Appointment.new(appointment_params)
    @appointment.user = current_user
    @appointment.offer = @offer

    if @appointment.save
      redirect_to user_path(current_user), notice: "Appointment was successfully booked."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @appointment = Appointment.find(params[:id])
    @offer = Offer.find(params[:offer_id])
  end

  def update
    @offer = Offer.find(params[:offer_id])
    @appointment = Appointment.find(params[:id])
    @appointment.offer = @offer

    @appointment.accepted = true
    @appointment.save!
    redirect_to user_appointments_path(current_user)
  end

  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_to user_appointments_path(current_user), status: :see_other
  end

  def index
    @appointments = Appointment.where(user_id: current_user.id)
  end

  private

  def appointment_params
    params.require(:appointment).permit(:start_date, :end_date, :hours)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @offers = Offer.all
    # The `geocoded` scope filters only offers with coordinates
    @markers = @offers.geocoded.map do |offer|
      {
        lat: offer.latitude,
        lng: offer.longitude
      }
    end

    if params[:query].present?
      @offers = @offers.where("location ILIKE ?", "%#{params[:query]}%")
    end

    if params[:category].present?
      @offers = @offers.where(category: params[:category])
    end

  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
      if @offer.save
        redirect_to @offer, notice: "Offer was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
  end

  def show
    @offer = Offer.find(params[:id])
    @markers = Array(@offer).map do |offer|
      {
        lat: offer.latitude,
        lng: offer.longitude,
        info_window: render_to_string(partial: "info_window", locals: {offer: offer})
      }
    end
  end

  def edit
    @offer = Offer.find(params[:id])
  end

  def update
    @offer = Offer.find(params[:id])
    @offer.update(offer_params)
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy
    redirect_to offers_path, notice: "Offer was successfully deleted."
  end

  private
  def offer_params
    params.require(:offer).permit(:title, :description, :hourly_rate, :location, :latitude, :longitude, :address, :photo, :category)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def home
  end

  def new
  end

  def create
  end

  def show

  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/_form.html.erb
<div class = "form">
  <%= simple_form_for [@offer, @appointment] do |f| %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.input :hours %>
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/appointments/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Owner</th>
      <th scope="col">Title</th>
      <th scope="col">Start Date</th>
      <th scope="col">End Date</th>
      <th scope="col">Hours</th>
      <th scope="col">Accept</th>
      <th scope="col">Decline</th>
      <th scope="col">Accepted</th>
    </tr>
  </thead>
  <tbody>
   <% count = 1 %>
      <% current_user.appointments.each do |appointment| %>
        <tr>
          <td> <%= count %> </td>
            <% count += 1 %>
          <td> <%=appointment.offer.user.email %> </td>
          <td> <%=appointment.offer.title %> </td>
          <td> <%=appointment.start_date %> </td>
          <td> <%=appointment.end_date %> </td>
          <td> <%=appointment.hours %> </td>
          <td> <%= button_to "Accept offer", offer_appointment_path(appointment.offer, appointment), method: :put, class: "btn btn-success" %></td>
          <td> <%= link_to "Decline offer", offer_appointment_path(appointment.offer, appointment), method: :delete,  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger text-light" %></td>
          <% if appointment.accepted == true %>
                <td> Yes </td>
                <% else %>
                <td> No </td>
                <% end %>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/appointments/new.html.erb
<div class = "container">
  <h1 class = "header">Book the appointment</h1>
  <%= render "form", Appointment: @appointment %>
  <br>
</div>
<div class = "button">
  <%= link_to "Back to profile", current_user, class:"btn btn-ghost" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
    <title>Helpingly</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
      <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/offers/_calendar.html.erb
<label for="start">Start date:</label>

<input type="date" id="start" name="trip-start"
       value="2018-07-22"
       min="2018-01-01" max="2018-12-31">

app/views/offers/_form.html.erb
<div class = "form">
  <%= simple_form_for(@offer) do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :hourly_rate %>
    <%= f.input :location %>
    <%= f.input :category, collection: %w[Home Sports Education Pets Arts Music Garden Other] %>
    <%= f.input :address,
    input_html: {data: {address_autocomplete_target: "address"}},
    wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
    %>
    <%= f.input :photo, as: :file%>

      <div class="form-actions">
        <%= f.button :submit, 'Save' %>
      </div>
  <% end %>
</div>

app/views/offers/_info_window.html.erb
<h2><%= offer.title %></h2>
<p><%= offer.address %></p>

app/views/offers/_user.html.erb
<div id="<%= dom_id offer %>">
  <p>
    <strong>Title:</strong>
    <%= user.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= user.description %>
  </p>
</div>

app/views/offers/edit.html.erb
<div class = "container">
  <h1 class = "header">Edit <%= @offer.title %> </h1>
  <%= render "form", Offer: @offer %>

  <br>
</div>

<div class = "button">
  <%= link_to "Back to my page", user_path(current_user), class:"btn btn-ghost" %>
</div>

app/views/offers/index.html.erb
<div class="section">
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <% @offers.each do |offer| %>
        <div class="carousel-item active">
        <%= link_to cl_image_tag(offer.photo.key, class: "d-block w-100", id: "banner"), offer_path(offer) %>
        <div class="carousel-caption d-none d-md-block">
          <h2> <%= offer.title %> </h2>
        </div>
      </div>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <section class="">
      <div class="container-search">
          <div class="row">
              <div class="col-lg-12">
                  <div class="row">
                    <div class="search-bar">
                      <%= form_with url: offers_path, method: :get, class: "d-flex" do %>
                        <%= text_field_tag :query,
                          params[:query],
                          class: "form-control",
                          placeholder: "Get some help in your city"
                        %>
                          <%= submit_tag "Search", class: "btn-ghost" %>
                      <% end %>
                    </div>
                  </div>
              </div>
          </div>
      </div>
  </section>
</div>


<div class="offers-section">
<div class="filter">

  <div class="home filter-icon">
    <%= link_to request.params.merge(category: "Home") do %>
      <i class="fa-solid fa-house"></i>
    <% end %>
    <p>Home</p>
  </div>

  <div class="sports filter-icon">
    <%= link_to request.params.merge(category: "Sports") do %>
      <i class="fa-solid fa-basketball"></i>
    <% end %>
    <p>Sports</p>
  </div>

  <div class="pets filter-icon">
    <%= link_to request.params.merge(category: "Pets") do %>
      <i class="fa-solid fa-dog"></i>
    <% end %>
    <p>Pets</p>
  </div>
  <div class="education filter-icon">
    <%= link_to request.params.merge(category: "Education") do %>
      <i class="fa-solid fa-book"></i>
    <% end %>
    <p>Education</p>
  </div>
  <div class="music filter-icon">
    <%= link_to request.params.merge(category: "Music") do %>
      <i class="fa-solid fa-music"></i>
    <% end %>
    <p>Music</p>
  </div>
  <div class="art filter-icon">
    <%= link_to request.params.merge(category: "Arts") do %>
      <i class="fa-solid fa-paintbrush"></i>
     <% end %>
    <p>Arts</p>
  </div>
  <div class="garden filter-icon">
    <%= link_to request.params.merge(category: "Garden") do %>
      <i class="fa-solid fa-tree"></i>
    <% end %>
    <p>Garden</p>
  </div>
  <div class="other filter-icon">
    <%= link_to request.params.merge(category: "Other") do %>
      <i class="fa-solid fa-question"></i>
    <% end %>
    <p>Other</p>
  </div>
</div>

  <h3 class="offers-text">Find help in your city</h3>
  <div id="offers" class="offerrsss"></div>
  <div class="grid" >
    <% @offers.each do |offer| %>
      <div class="g-col-md-4">
        <%= link_to(offer_path(offer), class: "card-link") do %>
          <div class="card-trip">
            <% if offer.photo.attached? %>
              <%= cl_image_tag offer.photo.key, height: 300, width: 400, crop: :fill %>
            <% end %>
            <div class="card-trip-infos">
              <div>
                <h2> <%= offer.title  %> </h2>
                <p><%= offer.description.truncate(30, separator: ' ') %> </p>
              </div>
              <h2 class="card-trip-pricing"> CHF <%= offer.hourly_rate  %> </h2>
            </div>
          </div>
        <% end %>
      </div>
    <%end%>
  </div>
</div>

app/views/offers/new.html.erb
<div class = "container">
  <h1 class = "header">Create a new offer</h1>
  <%= render "form", Offer: @offer %>

  <br>
</div>

<div class = "button">
  <%= link_to "Back to my page", user_path(current_user), class:"btn btn-ghost" %>
</div>

app/views/offers/show.html.erb
<div class="cont-wrapper">
  <div class="grid">
    <div class="g-col-6 m-3">
      <h1>
        <%= @offer.title %>
      </h1>
      <hr class="border border-dark border-2 opacity-50">
      <h4>
        <%= @offer.description %>
      </h4>
      <br>
      <div class = "pricelocation">
        <h5>CHF <%= @offer.hourly_rate %></h5>
        <h4><i class="fa-solid fa-location-dot"></i> <%= @offer.location %></h2>
      </div>
      <div class="booking">
        <%= link_to "Book", new_offer_appointment_path(@offer) %>
      </div>
      <hr class="border border-dark border-2 opacity-50" style="margin-top: 75px;">
    </div>
    <div class="g-col-6">
      <div class="g-col-6 g-col-md-4">
          <%= cl_image_tag(@offer.photo.key, width: 600, height: 500, crop: :fill) %>
      </div>
    </div>
  </div>
</div>

  <div class="more">
    <h3>MORE FROM THIS HELPER...</h3>
  </div>

<div class="grid">
  <% @offer.user.offers.excluding(@offer).each do |offer| %>
    <div class="g-col-md-4">
        <%= link_to(offer_path(offer), class: "card-link") do %>
          <div class="card-trip">
            <% if offer.photo.attached? %>
              <%= cl_image_tag offer.photo.key, height: 300, width: 400, crop: :fill %>
            <% end %>
            <div class="card-trip-infos">
              <div>
                <h2> <%= offer.title  %> </h2>
                <p><%= offer.description.truncate(30, separator: ' ') %> </p>
              </div>
              <h2 class="card-trip-pricing"> CHF <%= offer.hourly_rate  %> </h2>
            </div>
          </div>
        <% end %>
      </div>
  <% end %>
</div>

<div class="container">
  <div id="cool-map" style="width: 100%; height: 600px;"
    data-controller="map"
    data-map-markers-value="<%= Array(@markers).to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/shared/_card.html.erb
<div class="card-trip">
  <%= cl_image_tag offer.photo.key, height: 300, width: 400, crop: :fill %>
  <div class="card-trip-infos">
    <div>
      <h2> <%= offer.title  %> </h2>
      <p><%= offer.description  %> </p>
    </div>
      <h2 class="card-trip-pricing"><%= offer.hourly_rate  %> </h2>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This website is made with <i class="fas fa-heart"></i> at Helpingly
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg sticky-top shadow rounded grosor">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="active text-light" aria-current="page" href="#"><%= link_to "HELPINGLY", root_path, class: "navbutton nav-big" %></a>
        </li>
      </ul>
      <div class="navbar-right">
          <li class="dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <ion-icon name="person-circle-outline"></ion-icon>
          </a>
          <ul class="dropdown-menu">
          <% if user_signed_in? %>
            <li><%= link_to "My page", user_path(current_user), class: "dropdown-item" %></li>
            <li> <%= button_to "Log out", destroy_user_session_path, class: "dropdown-item", method: :delete, form: {"data-turbo": false} %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %> </li>
            <li><%= link_to "Log in", new_user_session_path, class: "dropdown-item" %></li>
          <% end %>
          </ul>
        </li>
      </div>
    </div>
  </div>
</nav>

app/views/users/_form.html.erb
<%= simple_form_for(@offer) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <%= f.input :photo, as: :file %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="page">
  <div class="left">
    <p> <%= image_tag 'https://images.unsplash.com/photo-1603415526960-f7e0328c63b1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cHJvZmlsZSUyMHBpY3R1cmV8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60', class: "profile_pic" %> </p>
      <h5> <%= current_user.email %> </h5>
      <div class="button">
      <%= link_to "Create a new offer", new_offer_path, class: "btn btn-ghost envelope" %>
    </div>
    <%= link_to(user_appointments_path(current_user), class: "card-link") do %>
      <i class="fa-solid fa-envelope"></i>
    <% end %>


  </div>
  <div class="right">
    <div class="header">
      <h2> Overview of my Offers </h2>
    </div>
    <div class="grid">
      <% current_user.offers.each do |offer| %>
        <div class="g-col-md-4">
          <%= link_to(offer_path(offer), class: "card-link") do %>
            <div class="card-trip">
              <%= cl_image_tag offer.photo.key, height: 200, width: 400, crop: :fill %>
              <div class="card-trip-infos">
                <div>
                  <h2> <%= offer.title  %> </h2>
                  <p><%= offer.description.truncate(30, separator: ' ') %> </p>
                </div>
                  <h2 class="card-trip-pricing">CHF <%= offer.hourly_rate  %> </h2>
              </div>
            </div>
            <div class="card-controllers">
              <%= link_to 'Delete', offer_path(offer), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'delete-card' %>
              <%= link_to 'Edit', edit_offer_path(offer), class: "edit-offer" %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

    <h2 id="booking-overview"> Overview of my Bookings </h2>
    <div class="bookings">

      <table class="table">
        <thead>
          <tr>
            <th scope="col">Owner</th>
            <th scope="col">Title</th>
            <th scope="col">Start Date</th>
            <th scope="col">End Date</th>
            <th scope="col">Hours</th>
            <th scope="col">Accepted?</th>
          </tr>
        </thead>
        <tbody>
            <% current_user.appointments.each do |appointment| %>
              <tr>
                <td> <%=appointment.offer.user.email %> </td>
                <td> <%=appointment.offer.title %> </td>
                <td> <%=appointment.start_date %> </td>
                <td> <%=appointment.end_date %> </td>
                <td> <%=appointment.hours %> </td>
                <% if appointment.accepted == true %>
                <td style="color: #475841"> Yes </td>
                <% else %>
                <td style="color: rgb(255, 0, 0)"> No </td>
                <% end %>
              </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>